package kz.allpay.mfs.webshop.keys;

import org.bouncycastle.openssl.PEMWriter;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.security.Key;

/**
 * User: Sanzhar Aubakirov
 * Date: 4/24/16
 */
public class KeySaver {

    /**
     * Use this method to Save the Signature and the Public Key in Files
     *
     * @param fileName name of created file
     * @param key      Public or Private key generated by {@link KeyGenerator}
     * @throws IOException if something goes wrong, usually I/O problems
     */
    public static void saveKeyToFile(final String fileName, final Key key) throws IOException {
        final FileOutputStream derFormat = new FileOutputStream(fileName + ".der");
        derFormat.write(key.getEncoded());
        derFormat.close();

        final File keyFile = new File(fileName + ".pem");
        final PEMWriter publicPemWriter = new PEMWriter(new FileWriter(keyFile));
        publicPemWriter.writeObject(key);
        publicPemWriter.flush();
        publicPemWriter.close();
    }

}
